---
name: Haskell CI

on:
  push:
    branches: ['**']

jobs:
  build_and_test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        plan:
          - {build: stack}

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Cache Stack
        id: cache-stack-unix
        uses: actions/cache@v3
        with:
          path: ~/.stack
          key: ${{ matrix.os }}-${{ matrix.plan.build }}-stack-home-${{ hashFiles('stack.yaml') }}-${{ hashFiles('package.yaml') }}

      - name: Setup stack
        uses: haskell/actions/setup@v2
        with:
          enable-stack: true
          stack-no-global: true

      - name: Install dependencies
        run: |
          set -ex
          stack --no-terminal --install-ghc test --bench --only-dependencies
          set +ex
        env:
          BUILD: ${{ matrix.plan.build }}

      - name: Build and test
        run: |
          set -ex
          stack --no-terminal test --coverage --bench --no-run-benchmarks --haddock --no-haddock-deps
          set +ex
        env:
          BUILD: ${{ matrix.plan.build }}
